config/routes.rb
Rails.application.routes.draw do
  root to: "root#home"
  get "search", as: "search", to: "root#search"

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:index, :destroy]
  
  resources :colleges, only: [:index, :show] do
    resources :college_ratings, only: [:new, :create]
    collection do
      get 'search'
    end
  end

  resources :professors, only: [:index, :show, :new, :create] do
    resources :professor_ratings, only: [:new, :create]
    collection do
      get 'search'
    end
  end

  resources :professor_ratings, only: [:edit, :update, :destroy]
  resources :college_ratings, only: [:edit, :update, :destroy]
  resources :up_down_votes, only: [:create, :destroy]
  
  namespace 'api', defaults: { format: :json } do
    get "search", as: "search", to: "root#search"
    
    resources :users, only: [:create, :show, :update]
    resource :session, only: [:create, :destroy]
    
    resources :colleges, only: [:index, :show] do
      resources :college_ratings, only: [:create]
      collection do
        get 'search'
      end
    end

    resources :professors, only: [:index, :show, :create] do
      resources :professor_ratings, only: [:create]
      collection do
        get 'search'
        get 'is_valid'
      end
    end
  
    resources :professor_ratings, only: [:index, :show, :update, :destroy]
    resources :college_ratings, only: [:index, :show, :update, :destroy]
    resources :up_down_votes, only: [:create, :destroy] do 
      collection do 
        get 'find_vote'
      end
    end
  end
  
  get '/auth/facebook/callback', to: 'oauth#facebook'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :session_token, :password_digest, presence: true
  validates :session_token, uniqueness: true
  validates :email, uniqueness: true, allow_nil: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validate :email_presence
  validate :check_if_valid_email

  attr_reader :password

  after_initialize :ensure_session_token

  belongs_to :college,
  class_name: "College",
  inverse_of: :students
  
  has_many :professor_ratings,
    foreign_key: :rater_id,
    inverse_of: :rater,
    dependent: :destroy
    
  has_many :professors,
    through: :professor_ratings,
    source: :professor
    
  has_many :college_ratings,
    foreign_key: :rater_id,
    inverse_of: :rater,
    dependent: :destroy
    
  has_many :up_down_votes,
    foreign_key: :voter_id,
    inverse_of: :voter,
    dependent: :destroy

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    if user
      if !user.is_password?(password)
        return nil
      end
    end

    return user
  end

  def self.generate_session_token
    loop do
      token = SecureRandom::urlsafe_base64(16)
      if !User.find_by_session_token(token)
        return token
      end
    end
  end
  
  def self.find_or_create_by_fb_auth_hash(auth_hash)
    user = User.find_by_uid(auth_hash.uid)
    
    unless user
      user = User.new(uid: auth_hash.uid, password: SecureRandom::urlsafe_base64(16))
      if auth_hash.info.first_name
        user.name = auth_hash.info.first_name
      elsif auth_hash.info.name
        user.name = auth_hash.info.name
      else
        user.name = "Facebook User"
      end
      
      if auth_hash.info.email
        user.email = auth_hash.info.email
      end
      
      user.save!
    end
    
    user
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def all_ratings
    professor_ratings = self.professor_ratings.includes(:professor).includes(:colleges)
 
    professor_ratings + self.college_ratings.includes(:college)
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def email_presence
    unless self.uid
      unless self.email
        errors.add(:email, "is missing")
      end
    end
  end
  
  def check_if_valid_email
    if self.email
      email_halves = self.email.split("@")
      if email_halves.length != 2
        errors.add(:email, "is not valid")
      elsif email_halves[0].length == 0
        errors.add(:email, "is not valid")
      elsif email_halves[1].split(".").length != 2
        errors.add(:email, "is not valid")
      elsif email_halves[1].split(".")[0].length == 0
        errors.add(:email, "is not valid")
      elsif email_halves[1].split(".")[1].length == 0
        errors.add(:email, "is not valid")
      end
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_filter :require_logged_in, only: [:show, :update]
  before_filter :require_logged_out, only: :create

  def create
    @user = User.new(user_params)

    if @user.save
      login_user(@user)
      render json: @user
    else
      render json: @user.errors.full_messages
    end
  end

  def show
    @user = User.find(params[:id])
    
    if @user.college_id
      @college = @user.college
    end
    @all_ratings = @user.all_ratings

    render :show
  end

  def update
    @user = current_user

    if @user.update(user_params)
      render json: @user
    else
      puts @user.errors.full_messages
      render json: @user.errors.full_messages, status: 422
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :college_id)
  end
  
  def require_logged_in
    redirect_to "#" + new_session_path unless logged_in?
  end
  
  def require_logged_out
    redirect_to "#" + user_path(current_user) if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_logged_in, only: [:show, :edit, :update]
  before_filter :require_logged_out, only: [:new, :create]
  before_filter :require_same_user, only: [:edit, :update]

  def new
    @user = User.new()
    @colleges = College.all

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notices] = ["User created!"]
      login_user(@user)
      redirect_to user_url(@user)
    else
      @colleges = College.all
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @all_ratings = @user.all_ratings

    render :show
  end

  def edit
    @user = current_user
    @colleges = College.all

    render :edit
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash[:notices] = ["User updated!"]
      redirect_to user_url(@user)
    else
      @colleges = College.all
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :college_id)
  end
  
  def require_same_user
    unless current_user.id == params[:id].to_i
      flash[:errors] = ["You can only edit your own info"]
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% action = user.persisted? ? user_url(user) : users_url %>
<% default_selected = user.persisted? ? "" : "selected" %>

<form action="<%= action %>" method="POST">
  <% if user.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>

  <%= authenticity_token %>

  <label for="user_name">Name</label>
  <input type="text"
      id="user_name"
      name="user[name]"
      value="<%= user.name %>">

  <label for="user_email">Email</label>
  <input type="email"
      id="user_email"
      name="user[email]"
      value="<%= user.email %>">


  <label for="user_college_id">College</label>
  <select name="user[college_id]" id="user_college_id">
    <option value="" <%= default_selected %>>--Select--</option>
    <% colleges.each do |college| %>
      <% selected = user.college_id == college.id ? "selected" : "" %>
      <option value="<%= college.id %>" <%= selected %>>
        <%= college.name %></option>
    <% end %>
  </select>

  <label for="user_password">Password</label>
  <input type="password"
      id="user_password"
      name="user[password]">

  <button><%= user.persisted? ? "Save" : "Sign Up" %></button>
</form>

app/views/users/edit.html.erb
<h1>Edit my info</h1>

<%= render "form", user: @user, colleges: @colleges %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user, colleges: @colleges %>

<%= link_to "Log In", new_session_url %>

app/views/users/show.html.erb
<section class="info">
  <h1><%= @user.name %></h1>
	
	<% if @user.email %>
	  <p><%= @user.email %></p>
	<% end %>
	
	<% if @user.college %>
  	<p><a href="<%= college_url(@user.college_id) %>"><%= @user.college.name %></a></p>
	<% end %>
	
  <%= link_to "Edit my info", edit_user_url(@user) %>
</section>


<section class="ratings">
  <h1>Ratings</h1>
	<ul>
		<% if @all_ratings.length > 0 %>
			<% @all_ratings.each do |rating| %>
				<li>
					<% if defined? rating.professor %>
						<a href="<%= professor_url(rating.professor) %>">
							<%= rating.professor.name %>, <%= rating.professor.department %> Department at 
							<%= rating.professor.college.name %>
						</a>
						<%= link_to "Edit", edit_professor_rating_url(rating) %>
						<%= button_to "Delete", professor_rating_url(rating), method: :delete %>
					<% else %>
						<a href="<%= college_url(rating.college) %>">
							<%= rating.college.name %>, <%= rating.college.location %>
						</a>
						<%= link_to "Edit", edit_college_rating_url(rating) %>
						<%= button_to "Delete", college_rating_url(rating), method: :delete %>
					<% end %>
				</li>
			<% end %>
		<% else %>
			<li>
				You have no ratings :(
				<a href="<%= professors_url %>">Rate a Professor</a>
				<a href="<%= colleges_url %>">Rate a College</a>
			</li>
		<% end %>
	</ul>
</section>