config/routes.rb
Rails.application.routes.draw do
  root to: "root#home"
  get "search", as: "search", to: "root#search"

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:index, :destroy]
  
  resources :colleges, only: [:index, :show] do
    resources :college_ratings, only: [:new, :create]
    collection do
      get 'search'
    end
  end

  resources :professors, only: [:index, :show, :new, :create] do
    resources :professor_ratings, only: [:new, :create]
    collection do
      get 'search'
    end
  end

  resources :professor_ratings, only: [:edit, :update, :destroy]
  resources :college_ratings, only: [:edit, :update, :destroy]
  resources :up_down_votes, only: [:create, :destroy]
  
  namespace 'api', defaults: { format: :json } do
    get "search", as: "search", to: "root#search"
    
    resources :users, only: [:create, :show, :update]
    resource :session, only: [:create, :destroy]
    
    resources :colleges, only: [:index, :show] do
      resources :college_ratings, only: [:create]
      collection do
        get 'search'
      end
    end

    resources :professors, only: [:index, :show, :create] do
      resources :professor_ratings, only: [:create]
      collection do
        get 'search'
        get 'is_valid'
      end
    end
  
    resources :professor_ratings, only: [:index, :show, :update, :destroy]
    resources :college_ratings, only: [:index, :show, :update, :destroy]
    resources :up_down_votes, only: [:create, :destroy] do 
      collection do 
        get 'find_vote'
      end
    end
  end
  
  get '/auth/facebook/callback', to: 'oauth#facebook'
end

app/views/shared/_footer.html.erb
<footer>
  <div class="home_link">
    <%= link_to "www.ratemypurrfessors.com", root_url %>
  </div>
  <div class="places_links">
    <ul>
    	<li><a href="#<%= colleges_path %>">Search/Rate Colleges</a></li>
			<li><a href="#<%= professors_path %>">Search/Rate Professors</a></li>
    </ul>
  </div>
	<div class="attribution">
		"Cat" symbol by <a href="http://www.thenounproject.com/isabelfoo">Isabel Foo</a>, from 
		<a href="http://thenounproject.com/">The Noun Project</a> collection.
	</div>
	<div class="attribution">
		"Institution" symbol by <a href="http://www.thenounproject.com/mikewirth">Mike Wirth</a>, from 
		<a href="http://www.thenounproject.com">The Noun Project</a> collection.
	</div>
</footer>

app/views/shared/_header.html.erb
<header class="group">
  <div class="logo"><a href="<%= root_url %>"><%= image_tag "RMP_Logo.png" %></a></div>
	
	<div class="nav_search">
		<form action="#<%= search_path %>" method="GET">
			<input type="search" name="match" placeholder="Search by college, professor, or department">
			<button>GO!</button>
		</form>
	</div>

  <div class="right_nav">
    <% if logged_in? %>
      <button class="user_nav">Hi, <%= current_user.name %></button>
      <ul class="user_dropdown">
        <li>
					<a href="#<%= user_path(current_user) %>">My Account</a>
        </li>
        <li>
          <%= button_to "Log Out", session_url, method: :delete %>
        </li>
      </ul>
    <% else %>
      <%= link_to "Log In/Sign Up", "#" + new_session_path, class: "user_nav" %>
    <% end %>
  </div>
</header>

app/views/shared/_notices.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<% if flash[:notices] %>
  <ul>
    <% flash[:notices].each do |notice| %>
      <li><%= notice %></li>
    <% end %>
  </ul>
<% end %>