config/routes.rb
Rails.application.routes.draw do
  root to: "root#home"
  get "search", as: "search", to: "root#search"

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:index, :destroy]
  
  resources :colleges, only: [:index, :show] do
    resources :college_ratings, only: [:new, :create]
    collection do
      get 'search'
    end
  end

  resources :professors, only: [:index, :show, :new, :create] do
    resources :professor_ratings, only: [:new, :create]
    collection do
      get 'search'
    end
  end

  resources :professor_ratings, only: [:edit, :update, :destroy]
  resources :college_ratings, only: [:edit, :update, :destroy]
  resources :up_down_votes, only: [:create, :destroy]
  
  namespace 'api', defaults: { format: :json } do
    get "search", as: "search", to: "root#search"
    
    resources :users, only: [:create, :show, :update]
    resource :session, only: [:create, :destroy]
    
    resources :colleges, only: [:index, :show] do
      resources :college_ratings, only: [:create]
      collection do
        get 'search'
      end
    end

    resources :professors, only: [:index, :show, :create] do
      resources :professor_ratings, only: [:create]
      collection do
        get 'search'
        get 'is_valid'
      end
    end
  
    resources :professor_ratings, only: [:index, :show, :update, :destroy]
    resources :college_ratings, only: [:index, :show, :update, :destroy]
    resources :up_down_votes, only: [:create, :destroy] do 
      collection do 
        get 'find_vote'
      end
    end
  end
  
  get '/auth/facebook/callback', to: 'oauth#facebook'
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  include PgSearch
  
  DEPARTMENTS = [
                "Agricatural Science",
                "Astrophysics",
                "Catfoodology",
                "Catonese",
                "Catstronomy",
                "Engineering",
                "Feline Studies",
                "Felosophy",
                "Fishics",
                "Fishology",
                "Fishtory",
                "Meowdern Art",
                "Meowndarin Chinese",
                "Meowsic",
                "Meowthematics",
                "Pawlitical Science",
                "Predator Biology",
                "Prey Biology",
                "Psycatogy",
                "Sleeping",
                "Textiles (Yarn Studies)",
                "Other"
                ]

  validates :first_name, :last_name, :college, :department, presence: true
  validates :college_id, uniqueness: { scope: [
                                            :first_name,
                                            :last_name,
                                            :middle_initial
                                            ]}

  belongs_to :college, inverse_of: :professors
  
  has_many :professor_ratings, inverse_of: :professor, dependent: :destroy
  
  has_many :up_down_votes, through: :professor_ratings, source: :up_down_votes
  
  multisearchable against: [:first_name, :middle_initial, :last_name, :department],
                  associated_against: { college: :name },
                  using: { tsearch: { 
                                    prefix: true,
                                    any_word: true 
                                    } }
                  
  pg_search_scope :search_professors, 
                      against: [:first_name, :middle_initial, :last_name, :department],
                      associated_against: { college: :name },
                      using: { tsearch: { 
                                        prefix: true,
                                        any_word: true 
                                        } }
                                        
  paginates_per 25

  def name
    name = "#{self.first_name} "
    name += "#{self.middle_initial} " if self.middle_initial
    name += self.last_name

    name
  end
  
  def avg_helpfulness
    return -1 if self.professor_ratings.length === 0
    
    total = self.professor_ratings.inject(0) do |accum, rating|
      accum + rating.helpfulness
    end
    
    (total * 10 / self.professor_ratings.length).round / 10.0
  end
  
  def avg_clarity
    return -1 if self.professor_ratings.length === 0
    
    total = self.professor_ratings.inject(0) do |accum, rating|
      accum + rating.clarity
    end
    
    (total * 10 / self.professor_ratings.length).round / 10.0
  end
  
  def avg_easiness
    return -1 if self.professor_ratings.length === 0
    
    total = self.professor_ratings.inject(0) do |accum, rating|
      accum + rating.easiness
    end
    
    (total * 10 / self.professor_ratings.length).round / 10.0
  end
  
  def avg_hotness
    return -1 if self.professor_ratings.length === 0
    
    total = self.professor_ratings.inject(0) do |accum, rating|
      accum + (rating.hotness ? 1 : 0)
    end
    
    total * 1.0 / self.professor_ratings.length
  end
end

app/controllers/api/professors_controller.rb
class Api::ProfessorsController < ApplicationController
  before_filter :require_logged_in, only: :create
  
  def index
    @professors = Professor.includes(:college).all

    render :index
  end

  def show
    @professor = Professor.includes(:professor_ratings).find(params[:id])

    render :show
  end

  def create
    @professor = Professor.new(professor_params)

    if @professor.save
      # redirect_to "#" + professor_path(@professor)
      render json: @professor
    else
      # redirect_to "#/professors/new"
      render json: @professor.errors.full_messages
    end
  end

  def search
    match = params[:match]
    @professors = Professor.search_professors(match).includes(:college)

    render :index
  end
  
  def is_valid
    @professor = Professor.new(professor_params)
    
    if @professor.valid?
      render json: @professor
    else
      render json: @professor.errors.full_messages
    end
  end
  
  private
  def require_logged_in
    unless logged_in?
      render json: "Must be logged in"
    end
  end
  
  def professor_params
    params.require(:professor).permit(
                                  :first_name,
                                  :middle_initial,
                                  :last_name,
                                  :department,
                                  :college_id,
                                  :filepicker_url
                                  )
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_filter :require_logged_in, only: [:new, :create]
  
  def index
    @professors = Professor.includes(:college).order(:last_name).page(params[:page])
    @header_text = "All Professors"

    render :index
  end

  def show
    @professor = Professor.find(params[:id])
    @ratings = @professor.professor_ratings.includes(:up_down_votes).page(params[:page])

    render :show
  end

  def new
    @professor = Professor.new
    @departments = Professor::DEPARTMENTS
    @colleges = College.all

    render :new
  end

  def create
    @professor = Professor.new(professor_params)

    if @professor.save
      flash[:notices] = ["Professor created!"]
      redirect_to professor_url(@professor)
    else
      @departments = Professor::DEPARTMENTS
      @colleges = College.all
      flash.now[:errors] = @professor.errors.full_messages
      render :new
    end
  end

  def search
    match = params[:match]
    @professors = Professor.search_professors(match).includes(:college)
    
    # match = params[:match]
#     all_professors = Professor.all
#
#     # store proper noun version of professor name for later
#     names = {}
#     all_professors.each do |professor|
#       cap = professor.name
#       down = cap.downcase
#       names[down] = cap
#     end
#
#     @professors = []
#     names.keys.each do |name|
#       if Regexp.new(match).match(name)
#         name = names[name]
#         professor = all_professors.select do |professor|
#           professor.name == name
#         end
#         @professors.push(professor.first)
#       end
#     end
#
    @header_text = 'Professors that match "' + match.html_safe + '":'

    render :index
  end

  private
  def professor_params
    params.require(:professor).permit(
                                  :first_name,
                                  :middle_initial,
                                  :last_name,
                                  :department,
                                  :college_id,
                                  :filepicker_url
                                  )
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/index.html.erb
<form action="<%= search_professors_url %>" method="GET" class="professor_search">
  <label for="match">Professor Search</label>
	
	<div class="professor_search group">
	  <input type="search" id="match" name="match" placeholder="Search by name, college, or department">
	  <button>Go!</button>
	</div>
</form>

<section class="professors_list">
  <p>
    Can't find your professor?
    <a href="<%= new_professor_url %>">Add a new one!</a>
  </p>

  <h1><%= @header_text %></h1>
	
  <ul>
    <% if @professors.length > 0 %>
      <% @professors.each do |professor| %>
        <li class="professor">
          <a href="<%= professor_url(professor) %>">
            <h3><%= professor.name %></h3>
            <p> <%= professor.department %> Department at
              <%= professor.college.name %></p>
          </a>
        </li>
      <% end %>
    <% else %>
      <li class="no_professors">No professors to show :(</li>
    <% end %>
  </ul>
	
</section>

app/views/professors/new.html.erb
<h1>Add New Professor</h1>

<form action="<%= professors_url %>" method="POST">
  <%= authenticity_token %>

  <label for="professor_first_name">First Name</label>
  <input type="text" 
  		name="professor[first_name]" 
  		id="professor_first_name"
  		value="<%= @professor.first_name %>">

  <label for="professor_middle_initial">Middle Initial</label>
  <input type="text" 
  		name="professor[middle_initial]" 
  		id="professor_middle_initial"
  		size="1"
  		value="<%= @professor.middle_initial %>">

  <label for="professor_last_name">Last Name</label>
  <input type="text" 
  		name="professor[last_name]" 
  		id="professor_last_name"
  		value="<%= @professor.last_name %>">

  <label for="professor_department">Department</label>
  <select name="professor[department]" id="professor_department">
    <option value="">--Select--</option>
    <% @departments.each do |department| %>
      <% selected = @professor.department == department ? "selected" : "" %>
      <option value="<%= department %>" <%= selected %>>
        <%= department %></option>
    <% end %>
  </select>

  <label for="professor_college_id">College</label>
  <select name="professor[college_id]" id="professor_college_id">
    <option value="">--Select--</option>
    <% @colleges.each do |college| %>
      <% selected = @professor.college_id == college.id ? "selected" : "" %>
      <option value="<%= college.id %>" <%= selected %>>
        <%= college.name %></option>
    <% end %>
  </select>

  <button>Add Professor</button>
</form>

app/views/professors/show.html.erb
<section class="professor_info">
	<%= filepicker_image_tag @professor.filepicker_url, w: 160, h: 160, fit: 'clip' %>
  <h1><%= @professor.name %></h1>
  <p><%= @professor.department %> Department</p>
  <p><a href="<%= college_url(@professor.college) %>"><%= @professor.college.name %></a></p>
	<%= link_to "Rate This Professor", new_professor_professor_rating_url(@professor) %>
</section>

<% if @professor.professor_ratings.length > 0 %>
	<section class="avg_ratings">
		<%= render "professor_ratings/averages", ratings: @professor.professor_ratings, professor: @professor %>
	</section>
<% end %>

<section class="ratings">
  <h1>Ratings</h1>
	
	<div class="paginate">
		<%= link_to_previous_page @ratings, 'Prev' %>
		<%= link_to_next_page @ratings, 'Next' %>
	</div>
	
	<ul>
		<% if @professor.professor_ratings.length > 0 %>
			<% @professor.professor_ratings.each do |rating| %>
				<li class="professor_rating">
					<%= render "professor_ratings/show", rating: rating %>
				</li>
			<% end %>
		<% else %>
		  <li>There are no ratings for this professor :(</li>
		<% end %>
	</ul>
	
	<div class="paginate">
		<%= link_to_previous_page @ratings, 'Prev' %>
		<%= link_to_next_page @ratings, 'Next' %>
	</div>
	
	<%= link_to "Rate This Professor", new_professor_professor_rating_url(@professor) %>
</section>