config/routes.rb
Rails.application.routes.draw do
  root to: "root#home"
  get "search", as: "search", to: "root#search"

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:index, :destroy]
  
  resources :colleges, only: [:index, :show] do
    resources :college_ratings, only: [:new, :create]
    collection do
      get 'search'
    end
  end

  resources :professors, only: [:index, :show, :new, :create] do
    resources :professor_ratings, only: [:new, :create]
    collection do
      get 'search'
    end
  end

  resources :professor_ratings, only: [:edit, :update, :destroy]
  resources :college_ratings, only: [:edit, :update, :destroy]
  resources :up_down_votes, only: [:create, :destroy]
  
  namespace 'api', defaults: { format: :json } do
    get "search", as: "search", to: "root#search"
    
    resources :users, only: [:create, :show, :update]
    resource :session, only: [:create, :destroy]
    
    resources :colleges, only: [:index, :show] do
      resources :college_ratings, only: [:create]
      collection do
        get 'search'
      end
    end

    resources :professors, only: [:index, :show, :create] do
      resources :professor_ratings, only: [:create]
      collection do
        get 'search'
        get 'is_valid'
      end
    end
  
    resources :professor_ratings, only: [:index, :show, :update, :destroy]
    resources :college_ratings, only: [:index, :show, :update, :destroy]
    resources :up_down_votes, only: [:create, :destroy] do 
      collection do 
        get 'find_vote'
      end
    end
  end
  
  get '/auth/facebook/callback', to: 'oauth#facebook'
end

app/controllers/api/root_controller.rb
class Api::RootController < ApplicationController
  def search
    match = params[:match]
    @matches = PgSearch.multisearch(match).includes(:searchable).map(&:searchable)
    
    render :search
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def home
    render :home
  end
  
  def search
    match = params[:match]
    @matches = PgSearch.multisearch(match).includes(:searchable).map(&:searchable)
    
    render :search
  end
end

app/views/root/home.html.erb
<div class="loading"></div>

<section class="filler"></section>
<div class="background_image"></div>

<section class="content">
  <p class="start">Get started...</p>
	
	<article>
		<div class="professor">
			<a href="<%= professors_url %>">
				<p>find/rate a</p>
				<strong>professor</strong>
			</a>
		</div>
		
		<div class="college">
			<a href="<%= colleges_url %>">
				<p>find/rate a</p>
				<strong>college</strong>
			</a>
		</div>
		
		<p class="main_label">
			Find
			<strong class="what">the thing</strong>
			<strong class="professor">the professor</strong>
			<strong class="college">the college</strong>
			you're looking for
		</p>
	</article>
</section>

<script id="departments">
	<%= Professor::DEPARTMENTS.to_json.html_safe %>
</script>

<script id="grad_years">
	<%= CollegeRating.grad_years.to_json.html_safe %>
</script>

<script id="grades">
	<%= ProfessorRating::GRADES.to_json.html_safe %>
</script>

<script id="current_user">
	<%= current_user.to_json.html_safe %>
</script>

app/views/root/search.html.erb
<form action="<%= search_url %>" method="GET">
  <label for="match">Search</label>
  <input type="search" id="match" name="match" placeholder="Search by college, professor, or department">

  <button>Go!</button>
</form>

<section class="matches_list">
  <h1><%= @header_text %></h1>

  <ul>
    <% if @matches.length > 0 %>
      <% @matches.each do |match| %>
        <li>
					<%# match = match.searchable %>
					<% if match.class == College %>
	          <a href="<%= college_url(match) %>">
	            <h3><%= match.name %></h3>
	            <p><%= match.location %></p>
	          </a>
					<% else %>
	          <a href="<%= professor_url(match) %>">
	            <h3><%= match.name %></h3>
	            <p> <%= match.department %> Department at
	              <%= match.college.name %></p>
	          </a>
					<% end %>
        </li>
      <% end %>
    <% else %>
      <li>There are no colleges or professors matching that search :(</li>
    <% end %>
  </ul>
</section>